chapters = {1: ['John the Baptist Prepares the Way',
   		       'The Baptism of Jesus',
		       'The Temptation of Jesus', 
		       'Jesus Begins His Ministry',
		       'Jesus Calls the First Disciples',
		       'Jesus Heals a Man With an Unclean Spirit',
		       'Jesus Heals Many',
		       'Jesus Preaches in Galilee',
		       'Jesus Cleanses a Leper'],
		           
		    2: ['Jesus Heals a Paralytic',
			    'Jesus Calls Levi',
			    'A Question About Fasting',
			    'Jesus is Lord of the Sabbath'],
			           
			3: ['A Man With a Withered Hand',
	            'A Great Crowd Follows Jesus',
	            'The Twelve Apostles',
	            'Blasphemy Against the Holy Spirit',
	            "Jesus' Mother and Brothers"],

	        4: ['The Parable of the Sower',
	            'The Purpose of the Parables',
	            'A Lamp Under a Basket',
	            'The Parable of the Seed Growing',
	            'The Parable of the Mustard Seed',
	            'Jesus Calms a Storm'],

	        5: ['Jesus Heals a Man With a Demon',
	            "Jesus Heals a Woman and Jairus' Daughter"],

	        6: ['Jesus Rejected at Nazareth',
	            'Jesus Sends Out the Twelve Apostles',
	            'The Death of John the Baptist',
	            "Jesus Feeds the Five-Thousand",
	            "Jesus Walks on Water",
	            "Jesus Heals the Sick in Gennasaret"],

	        7: ["Traditions and Commandments",
	            "What Defiles a Person",
	            "The Syrophoenician Woman's Faith",
	            "Jesus Heals a Deaf Man"],

	        8: ["Jesus Feeds the Four-Thousand",
	            "The Pharisees Demand a Sign",
	            "The Leaven of the Pharisees and Herod",
	            "Jesus Heals a Blind Man at Bethsaida",
	            "Peter Confesses Jesus as the Christ",
	            "Jesus Foretells His Death and Resurrection"],

	        9: ["The Transfiguration",
	            "Jesus Heals a Boy With an Unclean Spirit",
	            "Jesus Again Foretells Death, Resurrection",
	            "Who is the Greatest?",
	            "Anyone Not Against Us is For Us",
	            "Temptations to Sin"],

	        10: ["Teaching About Divorce",
	             "Let the Children Come to Me",
	             "The Rich Young Man",
	             "Jesus Foretells His Death a Third Time",
	             "The Request of James and John",
	             "Jesus Heals Blind Bartimaeus"],

	        11: ["The Triumphal Entry",
	             "Jesus Curses the Fig Tree",
	             "Jesus Cleanses the Temple",
	             "The Lesson From the Withered Fig Tree",
	             "The Authority of Jesus Challenged"],

	        12: ["The Parable of the Tenants",
	             "Paying Taxes to Caesar",
	             "The Sadducees Ask About the Resurrection",
	             "The Great Commandment",
	             "Whose Son Is the Christ?",
	             "Beware of the Scribes",
	             "The Widow's Offering"],

	        13: ["Jesus Foretells Destruction of the Temple",
	             "Signs of the Close of the Age",
	             "The Abomination of Desolation",
	             "The Coming of the Son of Man",
	             "The Lesson of the Fig Tree",
	             "No One Knows That Day or Hour"],

	        14: ["The Plot to Kill Jesus",
	             "Jesus Anointed At Bethany",
	             "Judas to Betray Jesus",
	             "The Passover With the Disciples",
	             "Institution of the Lord's Supper",
	             "Jesus Foretells Peter's Denial",
	             "Jesus Prays in Gethsemane",
	             "Betrayal and Arrest of Jesus",
	             "A Young Man Flees",
	             "Jesus Before the Council",
	             "Peter Denies Jesus"],

	        15: ["Jesus Delivered to Pilate",
	             "Pilate Delivers Jesus to be Crucified",
	             "Jesus is Mocked",
	             "The Crucifixion",
	             "The Death of Jesus",
	             "Jesus is Buried"],

	        16: ["The Resurrection",
	             "Jesus Appears to Mary Magdalene",
	             "Jesus Appears to Two Disciples",
	             "The Great Commission"]}